### ISSUE TITLE
How to use the library in Android Studio project

### ISSUE THREAD

**Issue by zulluadi** [Birdbrain2/PdfBox-Android#54]
Hi, I can't figure it out how should I import or use the library in my own project. Can you please give me a step by step usage guide or something similar? 

Thank you in advance.

**Comment by Birdbrain2** [comment]
[This link should help you get setup.](http://stackoverflow.com/questions/16595287/how-to-import-maven-dependency-in-android-studio-intellij) The library is available on jcenter, so all you need to do is declare it as a dependency. In the build.gradle of your project, you need to add ```compile 'org.apache:pdfbox-android:1.8.9.0'``` to the dependencies section. I believe jcenter is now the default repository in Android Studio, so that should be it. If it's not, you need to add ```jcenter()``` to the repositories section of our build.gradle.
